"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.getenv("DEBUG", "False") == "True"
DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"

ALLOWED_HOSTS = [
    'http://localhost',
    '127.0.0.1',
    'jbearlocal.com',
    "jmeyer-dev.com", 
    "jbear-creations.com", 
    "jbearcreations.com",
    "vet-cal.jmeyer-dev.com",  # MUST INCLUDE DOMAIN to avoid CORS issues
    "vet-backend.jmeyer-dev.com",  # MUST INCLUDE DOMAIN to avoid CORS issues
]

CORS_ORIGIN_WHITELIST = [
    'http://localhost:9000',
    'http://127.0.0.1:9000',
    'http://localhost',
    "https://jmeyer-dev.com", 
    "https://jbear-creations.com", 
    "https://jbearcreations.com",
    "https://vet-cal.jmeyer-dev.com",
    "https://vet-backend.jmeyer-dev.com",
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:9000/*',
    'http://*.127.0.0.1',
    "https://jmeyer-dev.com/*", 
    "https://jbear-creations.com/*", 
    "https://jbearcreations.com/*",
    "https://vet-cal.jmeyer-dev.com/*",
    "https://vet-backend.jmeyer-dev.com/*",
]
    

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'VetCalendar',
    'login',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware'
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [], # local
        'DIRS': [os.path.join(BASE_DIR,'templates')], #cPanel
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    # 'default': { # MySQL Settings
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': os.getenv('DB_TABLE'),
    #     'USER': os.getenv('DB_USER'),
    #     'PASSWORD': os.getenv('DB_PASS'),
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    #     'OPTIONS': {  
    #         'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"  
    #     }
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles' # 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    'VetCalendar/static/',
    # 'ShiftScheduler/static/',
]
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles") #local
STATIC_ROOT = os.path.join(BASE_DIR, 'public') # cPanel

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "tmp") # cPanel

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
